version: '3'

services:
  database:
    container_name: database
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: test_user
      MYSQL_PASSWORD: qaz123
      MYSQL_DATABASE: USERS_DB
    restart: always
    ports:
      - "3306:3306"

  configuration-service:
    container_name: configuration-service
    image: pl.betse.beontime/configuration-service:latest
    restart: always
    ports:
      - "8888:8888"

  registry-service:
    container_name: registry-service
    image: pl.betse.beontime/registry-service:latest
    environment:
      - CONFIG_SERVER_URL=http://configuration-service:8888
    restart: always
    ports:
      - "8761:8761"
    links:
      - configuration-service:configuration-service

  gateway-service:
    container_name: gateway-service
    image: pl.betse.beontime/gateway-service:latest
    environment:
      - CONFIG_SERVER_URL=http://configuration-service:8888
      - REGISTRY_URL=http://registry-service:8761/eureka/
    restart: always
    ports:
      - "8080:8080"
    links:
      - configuration-service:configuration-service
      - registry-service:registry-service

  users-service:
    container_name: users-service
    image: pl.betse.beontime/users-service:latest
    environment:
      - CONFIG_SERVER_URL=http://configuration-service:8888
      - REGISTRY_URL=http://registry-service:8761/eureka/
      - DATABASE_URL=jdbc:mysql://database:3306/USERS_DB?createDatabaseIfNotExist=true&serverTimezone=CET
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    restart: always
    links:
      - configuration-service:configuration-service
      - registry-service:registry-service
      - database:database

  authentication-service:
    container_name: authentication-service
    image: pl.betse.beontime/authentication-service:latest
    environment:
      - CONFIG_SERVER_URL=http://configuration-service:8888
      - REGISTRY_URL=http://registry-service:8761/eureka/
    restart: always
    links:
      - configuration-service:configuration-service
      - registry-service:registry-service

  projects-service:
    container_name: projects-service
    image: pl.betse.beontime/projects-service:latest
    environment:
      - CONFIG_SERVER_URL=http://configuration-service:8888
      - REGISTRY_URL=http://registry-service:8761/eureka/
      - DATABASE_URL=jdbc:mysql://database:3306/PROJECTS_DB?createDatabaseIfNotExist=true&serverTimezone=CET
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    restart: always
    links:
      - configuration-service:configuration-service
      - registry-service:registry-service
      - database:database
    ports:
      - "4444:4444"

  timesheet-service:
    container_name: timesheet-service
    image: pl.betse.beontime/timesheet-service:latest
    environment:
      - CONFIG_SERVER_URL=http://configuration-service:8888
      - REGISTRY_URL=http://registry-service:8761/eureka/
      - DATABASE_URL=jdbc:mysql://database:3306/TIMESHEET_DB?createDatabaseIfNotExist=true&serverTimezone=CET
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    restart: always
    links:
      - configuration-service:configuration-service
      - registry-service:registry-service
      - database:database